Correlation id utilities (GSI 501)
ghga-de/hexkit pull request #74
Opened 2023-11-30 13:47 UTC by TheByronHimes

This adds the correlation ID utilities as outlined in the Marabou Stork epic.
This PR only adds the utilities and does not modify the behavior of the Kafka providers (that will come next). 
The new stuff:

### Functions
- `get_correlation_id()`
- `new_correlation_id()`
- `set_correlation_id()`
- `validate_correlation_id()`
- `set_context_var()`

### Errors
- `CorrelationIdContextError`
- `InvalidCorrelationIdError`
- `MissingCorrelationIdError`
I think `MissingCorrelationIdError` could be folded into the `InvalidCorrelationIdError` as it's only used in `set_correlation_id` to differentiate between an empty string vs an invalid non-empty string.

### Other
- `correlation_id_var`: The ContextVar instance that is used to store/access a correlation ID for a context.

2023-12-01 11:12 UTC, mephenor submitted a review, later dismissed
Looks nice. Personally I'd fold the CorrelationIDContext and MissingContextID errors into one, don't see a reason to keep them separate if we don't necessarily need to distinguish between unset and empty ID.

2023-12-04 09:21 UTC, mephenor approved these changes

2023-12-05 09:13 UTC, Cito requested changes
Looks good, just some suggestions regarding the testing.

2023-12-05 09:13 UTC, Cito commented on tests/unit/test_correlation.py
> +        (new_correlation_id(), None),
Creating the new id is actually also non-deterministic, but I think we can live with it here.

2023-12-05 09:13 UTC, Cito commented on tests/unit/test_correlation.py
> +        (new_correlation_id(), None),
But maybe also add a fixed valid value before that line.

2023-12-05 09:13 UTC, Cito commented on tests/unit/test_correlation.py
> +        (new_correlation_id(), None),
same here

2023-12-05 09:13 UTC, Cito commented on tests/unit/test_correlation.py
> +        # Ensure the value that is reset is actually the previous token, not just default
```suggestion
        # Ensure the value that is reset is actually the previous value, not just default
```

2023-12-05 11:27 UTC, TheByronHimes commented
@Cito please see the changes in [24dce0f](https://github.com/ghga-de/hexkit/pull/74/commits/24dce0fe7e31864ac45782008bb99f6cc2cdd236) and resolve the conversations if you are satisfied. I'm happy to make further modifications if needed.

2023-12-05 11:59 UTC, Cito approved these changes
Thanks for the changes.

2023-12-05 13:18 UTC, merged